# # docker-compose.yaml
# version: '3.8'
# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     privileged: true
#     user: root
#     ports:
#       - 8080:8080
#       - 50000:50000
#     container_name: jenkins
#     volumes:
#       - /home/ubuntu/docker/jenkins_configuration:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - mynetwork
#   sonarqube:
#     image: sonarqube
#     depends-on:
#       - db
#     restart: unless-stopped
#     environment:
#       - SONARQUBE_JDBC_USERNAME=sonarqube
#       - SONARQUBE_JDBC_PASSWORD=sonarpass
#       - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
#     ports:
#       - "9000:9000"
#       - "9092:9092"
#     volumes:
#       - sonarqube_conf:/opt/sonarqube/conf
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#     networks:
#       - mynetwork
#   db:
#     image: postgres
#     restart: unless-stopped
#     environment:
#       - POSTGRES_USER=sonarqube
#       - POSTGRES_PASSWORD=sonarpass
#       - POSTGRES_DB=sonarqube
#     volumes:
#       - sonarqube_db:/var/lib/postgresql
#       - postgresql_data:/var/lib/postgresql/data
#     networks:
#       - mynetwork
# volumes:
# postgresql_data:
# sonarqube_bundled-plugins:
# sonarqube_conf:
# sonarqube_data:
# sonarqube_db:
# sonarqube_extensions:
# networks:
#   mynetwork:
#     driver: bridge

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/ubuntu/docker/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
  sonarqube:
    image: sonarqube
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - mynetwork
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - mynetwork
volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
networks:
  mynetwork:
    driver: bridge
